Move channelId to secret
TheVaultdweller13/dado-bot pull request #32
Opened 2021-10-29 18:55 UTC by TheVaultdweller13

Resolves #29

2021-10-29 18:56 UTC, TheVaultdweller13 commented
Para la revisión faltaría meter la variable en HEROKU.

2021-10-30 10:58 UTC, Nirei requested changes

2021-10-30 10:58 UTC, Nirei commented on .github/workflows/heroku-deployment-dev-manual.yml
> +          heroku_channel_id: ${{secrets.HEROKU_CHANNEL_ID}}
Estas variables son para el plan de despliegue en sí, las variables de la aplicación van directamente en Heroku y no hace falta ponerlas aquí (ni dar de alta el secret).

(No es que no haga falta, es que no se puede usar este valor desde Heroku.)

2021-10-30 10:58 UTC, Nirei commented on bot.js
> +const channelId = process.env.CHANNEL_ID;
Doy de alta en heroku la variable del entorno CHANNEL_ID tanto para development como para producción.

2021-10-30 10:58 UTC, Nirei commented on bot.js
> +        channelId ? client.channels.cache.get(channelId).send('¡dado-bot se ha conectado!') : undefined;
Ese `undefined` me queda un poco feo, mi recomendación sería hacer esto mismo con `&&`.

```js
channelId && client.channels.cache.get(channelId).send('¡dado-bot se ha conectado!');
```

Si no tiene un valor verdadero `channelId`, la segunda parte ya no se evalúa. Es más idiomático en JS/Node y te ahorra un `undefined` que realmente no usas.

Es típico de hecho en React:

```{ condicion && (<>Cosas en React que solo se renderizan si condicion se cumple</>) }```

2021-10-30 11:09 UTC, TheVaultdweller13 commented on bot.js
> +        channelId ? client.channels.cache.get(channelId).send('¡dado-bot se ha conectado!') : undefined;
Coño, cierto. De hecho le estuve dando vueltas porque el undefined no me molaba nada, y no me acordé del `&&`.

2021-10-30 17:54 UTC, Nirei approved these changes

2021-10-30 19:38 UTC, merged